# Generated by Django 4.2.2 on 2023-06-21 05:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_transaction_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="credit_score",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("10"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="total_budget",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
