# Generated by Django 4.2.2 on 2023-06-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_student_credit_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorybudget",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
