# Generated by Django 4.2.2 on 2023-06-21 18:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_categorybudget_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="total_budget",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
    ]
