# Generated by Django 4.2.2 on 2023-06-23 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_student_total_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
    ]
