# Generated by Django 4.2.2 on 2023-06-23 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date", "id"]},
        ),
    ]
