# Generated by Django 4.2.2 on 2023-06-25 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_transaction_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(20)]
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("upvotes", models.IntegerField(default=0)),
                (
                    "bookmarked_by",
                    models.ManyToManyField(
                        related_name="bookmarked_posts", to="api.student"
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        related_name="liked_posts", to="api.student"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="api.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(20)]
                    ),
                ),
                ("upvotes", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "liked_by",
                    models.ManyToManyField(
                        related_name="liked_comments", to="api.student"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.communitypost",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.student",
                    ),
                ),
            ],
        ),
    ]
