# Generated by Django 4.2.2 on 2023-06-25 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_communitypost_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 25, 10, 30, 48, 357660, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
