# Generated by Django 4.2.2 on 2023-06-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_communitypost_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-upvotes"]},
        ),
        migrations.AlterModelOptions(
            name="communitypost",
            options={"ordering": ["-upvotes"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to="api.student"
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="bookmarked_by",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_posts", to="api.student"
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to="api.student"
            ),
        ),
    ]
