# Generated by Django 4.2.2 on 2023-06-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_comment_options_alter_communitypost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
    ]
